package com.Crowdsourcing.scenery;

public enum SceneryEventType
{
	GAME_OBJECT_SPAWNED,
	GAME_OBJECT_DESPAWNED,
	GAME_OBJECT_CHANGED,
	WALL_OBJECT_SPAWNED,
	WALL_OBJECT_DESPAWNED,
	WALL_OBJECT_CHANGED,
	DECORATIVE_OBJECT_SPAWNED,
	DECORATIVE_OBJECT_DESPAWNED,
	DECORATIVE_OBJECT_CHANGED,
	GROUND_OBJECT_SPAWNED,
	GROUND_OBJECT_DESPAWNED,
	GROUND_OBJECT_CHANGED
}
